Feat error logging
AudioNook/IT490-002 pull request #105
Opened 2023-03-17 16:51 UTC by jmpearson135

Added a function to call for logging errors the format is logIT('errorType', 'error', '__LINE__', '__FILE__').
Error type can be 'db', 'frontend',  'api'. 
Error what ever is caught with the try catch. 
__LINE__ and __FILE__ put in the function exactly like that and will automatically grab the line # and file name. 
![image](https://user-images.githubusercontent.com/123332874/225964828-47d3775f-5feb-4e95-bca5-76762a9d2681.png)

Added code for four logServers for each virtual machine so that the logs can be grabbed from each persons rabbit queue and saved to their individual vm so all logs are shared. 
![image](https://user-images.githubusercontent.com/123332874/225965755-046e2794-1287-4b2d-971e-9abc033d4587.png)

Modified config.php files for new rabbitmq exchanges and queues for logging. 
![image](https://user-images.githubusercontent.com/123332874/225966387-0c7e9f2f-023b-46e9-bfcd-3594a015f909.png)

Added new server information to rabbitMQ.ini file.
![image](https://user-images.githubusercontent.com/123332874/225966744-72b6d63e-9d9a-4b18-b1e6-ce46c7538807.png)

Added logIT function to request handling pages in catch statements. 

![image](https://user-images.githubusercontent.com/123332874/225967285-a068f14e-4225-448b-8bac-115e36d463ce.png)
![image](https://user-images.githubusercontent.com/123332874/225967346-4d54660d-76b2-4336-9dfe-6c9d927e0002.png)
![image](https://user-images.githubusercontent.com/123332874/225967392-d6f7b2c2-5277-4649-99ac-5913e97a2e08.png)

2023-03-17 17:36 UTC, Carlomos7 requested changes

2023-03-17 17:36 UTC, Carlomos7 commented on data/configuration/config.php
you can remove this since it's set in data/RabbitMQ/rbMQconfig.php:

2023-03-17 17:36 UTC, Carlomos7 commented on scripts/rabbitMQserver.php
> +            $response = handle_register($request["username"],$request["password"]);
This change overrides the email value provided

2023-03-17 17:36 UTC, Carlomos7 commented on src/lib/config.php
>  <?php
Remove to not override config.php

2023-03-17 17:36 UTC, Carlomos7 commented on src/lib/jwt_handling/generate_jwt.php
>  function generate_jwt($db, $user){
Merge Conflict

2023-03-17 17:36 UTC, Carlomos7 commented on src/lib/jwt_handling/validate_jwt.php
>      $key = JWT_SECRET;
Merge conflict

2023-03-17 17:36 UTC, Carlomos7 commented on src/lib/request_handling/handle_register.php
>  <?php
Merge Conflict

2023-03-17 17:36 UTC, Carlomos7 commented on src/lib/request_handling/handle_logout.php
>  function handle_logout($jwt){
Merge conflict

2023-03-17 17:36 UTC, Carlomos7 commented on src/lib/request_handling/handle_login.php
> +        $stmt = $db->prepare("SELECT id, username, password FROM testusers WHERE username = :username");
Merge Conflict

2023-03-17 17:52 UTC, Carlomos7 requested changes

2023-03-18 05:46 UTC, jmpearson135 commented on scripts/jaylinErrorLogging.php
> +             logError($error, '/var/www/sample/data/logs/apiErrors');
Fixed the directory paths in the logging files and changed the apiErrors file name. 
https://github.com/AudioNook/IT490-002/pull/105/commits/590387c069b37a9cf1f42f5030cdefa84bf1d91d
https://github.com/AudioNook/IT490-002/pull/105/commits/2f9b256956c869c1f8e3f21f6bfd35344cd35426
https://github.com/AudioNook/IT490-002/pull/105/commits/20511d59365e8dbe045c498e831e499939bbea20
https://github.com/AudioNook/IT490-002/pull/105/commits/7ac5e5d34e947b82649be8d2673a826edda51ab4
https://github.com/AudioNook/IT490-002/pull/105/commits/baea5abd1d0b6fb77caa6f1103475045825abc67
https://github.com/AudioNook/IT490-002/pull/105/commits/8083a542ac2b562408d32f65d2a98f9d286f42b7
https://github.com/AudioNook/IT490-002/pull/105/commits/0ff297b66bfc44bd17d954813f71ba6131bb600a
https://github.com/AudioNook/IT490-002/pull/105/commits/69654771564d03f535b26bab98b45b47bbf4b705

2023-03-18 05:47 UTC, Carlomos7 approved these changes

2023-03-18 05:48 UTC, merged